=== pauolt/LenguajesDeMarca/2.ExercicisDTD/5.ExercicisXMLDTD/aeroport.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT aeroport (nom, vols+)>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT vols (diari?, origen, desti, eixida, arribada)>
        <!ATTLIST vols codi ID #REQUIRED>
        <!ATTLIST vols estat (C | E | R ) "E">
        <!ELEMENT diari (EMPTY?)>
        <!ELEMENT origen (#PCDATA)>
        <!ELEMENT desti (#PCDATA)>
        <!ELEMENT eixida (#PCDATA)>
        <!ELEMENT arribada (#PCDATA)>

=== pauolt/LenguajesDeMarca/2.ExercicisDTD/5.ExercicisXMLDTD/aeroport.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE aeroport SYSTEM "aeroport.dtd">
<aeroport>
    <nom>JFK</nom>
    <vols codi="V22" estat="R">
        <diari/>
        <origen>New York</origen>
        <desti>Chicago</desti>
        <eixida>9:30</eixida>
        <arribada>11:30</arribada>
    </vols>
    <vols codi="V23" estat="C">
        <origen>New York</origen>
        <desti>Miami</desti>
        <eixida>10:15</eixida>
        <arribada>11:15</arribada>
    </vols>
</aeroport>
