<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE socios [
        <!ELEMENT socios (socio*)>
        <!ELEMENT socio (numero?, clave?, nombre, edad?)>
        <!ELEMENT clave (#PCDATA)>
        <!ELEMENT numero (#PCDATA)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT edad (#PCDATA)>
        ]>
<socios>
    <socio>
        <nombre>Ana</nombre>
        <edad>21</edad>
    </socio>
    <socio>
        <numero>598</numero>
        <nombre>Iker</nombre>
        <edad>19</edad>
    </socio>
    <socio>
        <clave>hY75Du</clave>
        <nombre>Iker</nombre>
    </socio>
</socios>